version: '2.1'

services:
  # client:
  #   restart: always
  #   build: .
  #   ports:  
  #     - 4000:3000
  #   command: "npm start"
  #   volumes:
  #     - ./app/ui:/app
  #     - /app/node_modules/

  flask_app:
    restart: always
    build: .
    ports:  
      - 3000:4000
    volumes:
      - .:/app
    depends_on:
      - redis
    # entrypoint: ["python", "run.py"]
    command: gunicorn -w 4 -b "0.0.0.0:4000" run:app

  redis:
    restart: always
    image: redis
    volumes:
      - ./redis_data:/data:cached

  celery:
    restart: always
    build: .
    command: celery worker -A celery_worker.celery --loglevel=info

volumes:
  redis_data:
    external:
      name: redis_data
